pipeline {
    agent any

    tools {
        maven 'Maven-3.9'   // nombre configurado en Global Tool Configuration
    }

    environment {
        REGISTRY = "demishuaccha/tingeso-m"
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Build with Maven') {
            steps {
                dir('tingesoM/tingesoM') {
                    sh "mvn clean package -DskipTests"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('tingesoM/tingesoM') {
                    sh "docker build -t ${REGISTRY}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds',
                                                 usernameVariable: 'DOCKER_USER',
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${REGISTRY}:${IMAGE_TAG}"
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                dir('tingesoM/tingesoM') {
                    sh """
                        docker compose stop
                        docker compose rm -f
                        docker compose up -d
                    """
                }
            }
        }
    }
}

