pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
    }

    environment {
        REGISTRY = "demishuaccha/tingeso-m"
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Build with Maven') {
            steps {
                dir('tingesoM/tingesoM') {
                    script {
                        def cmd = "mvn clean package -DskipTests"
                        if (isUnix()) {
                            sh cmd
                        } else {
                            bat cmd
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('tingesoM/tingesoM') {
                    script {
                        def cmd = "docker build -t ${REGISTRY}:${IMAGE_TAG} ."
                        if (isUnix()) {
                            sh cmd
                        } else {
                            bat cmd
                        }
                    }
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds',
                                                 usernameVariable: 'DOCKER_USER',
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        def cmd = "echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin"
                        if (isUnix()) {
                            sh cmd
                        } else {
                            bat cmd
                        }
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    def cmd = "docker push ${REGISTRY}:${IMAGE_TAG}"
                    if (isUnix()) {
                        sh cmd
                    } else {
                        bat cmd
                    }
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                dir('tingesoM/tingesoM') {
                    script {
                        def cmd = """
                            docker compose stop
                            docker compose rm -f
                            docker compose up -d
                        """
                        if (isUnix()) {
                            sh cmd
                        } else {
                            bat cmd
                        }
                    }
                }
            }
        }
    }
}
